services:

  redis:
    image: redis:7.4.2@sha256:93a8d83b707d0d6a1b9186edecca2e37f83722ae0e398aee4eea0ff17c2fad0e
    ports:
      - "6379:6379"

  solr:
    image: ckan/ckan-solr:2.11-solr9@sha256:166c7e832601de81f18389fd25d323f98d18b57c42acdc8dfe9a9d8e58e8cda6
    ports:
        - "8983:8983"
    volumes:
      - solr:/opt/solr/server

  db:
    # built from hasadna/ckan-cloud-docker
    image: datacity/db@sha256:ce470012de0ca1856ecca148e39bc892fbf95481826e5e4d46aadb997b188fd7
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  solr:
  datastore-db:
