SETTINGS_REDIS_KEY_PREFIX = "ckanext:datacity:settings"

HOMEPAGE_GROUPS_REDIS_KEY = "ckanext:datacity:homepage:groups"
HOMEPAGE_GROUPS_REDIS_KEY_EXPIRES_SECONDS = 60

HOMEPAGE_POPULAR_DATASETS_REDIS_KEY = "ckanext:datacity:homepage:popular_datasets"
HOMEPAGE_POPULAR_DATASETS_REDIS_KEY_EXPIRES_SECONDS = 60

HOMEPAGE_LAST_UPDATED_DATASETS_REDIS_KEY = "ckanext:datacity:homepage:last_updated_datasets"
HOMEPAGE_LAST_UPDATED_DATASETS_REDIS_KEY_EXPIRES_SECONDS = 60
